# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='votes',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(max_length=14, null=True),
        ),
    ]
