# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oscars', '0002_auto_20190318_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='oscars.Profile'),
        ),
    ]
