# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-16 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('oscars', '0002_auto_20190314_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', pyuploadcare.dj.models.ImageField()),
                ('url', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
