# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscars', '0002_auto_20190318_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Bio',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
